apiVersion: apps/v1
kind: Deployment
metadata:
  name: real-world-api
  namespace: real-world
  labels:
    app: real-world-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: real-world-api
  template:
    metadata:
      labels:
        app: real-world-api
    spec:
      hostAliases:
      - ip: "10.233.33.73"
        hostnames:
        - "harbor.andrealbuquerque.me"
      imagePullSecrets:
        - name: harbor-robot
      containers:
        - name: real-world-api
          image: harbor.andrealbuquerque.me/andrealbuquerqueme/real-world-api:b81f98f3b5
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          env:
            - name: NODE_ENV
              value: "production"