apiVersion: v1
kind: Secret
metadata:
  name: harbor-robot
  namespace: real-world
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "harbor-registry.harbor.svc.cluster.local:5000": {
          "username": "robot$andrealbuquerque+k8s-pull",
          "password": "hKfAdjZoL3vy2SD3kys53aTTl04Lm0JO"
        }
      }
    }