apiVersion: v1
kind: Secret
metadata:
  name: harbor-robot
  namespace: real-world
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "harbor-registry.harbor.svc.cluster.local:5000": {
          "username": "robot$andrealbuquerqueme+k8s-pull",
          "password": "PbcFRPbQ0STgDlF86IjG7fCegBG7SQTp",
          "auth": "cm9ib3QkYW5kcmVhbGJ1cXVlcnF1ZStrOHMtcHVsbDpoS2ZBZGpab0wzdnkyU0Qza3lzNTNhVFRsMDRMbTBKTw=="
        }
      }
    }