apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: real-world-api

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - namespace.yaml

secretGenerator:
  - name: harbor-robot
    files:
      - .dockerconfigjson=harbor.json
    type: kubernetes.io/dockerconfigjson

generatorOptions:
  disableNameSuffixHash: false