apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins
spec:
  serviceAccountName: jenkins-ci
  hostAliases:
  - ip: "192.168.1.150"
    hostnames:
    - "harbor.andrealbuquerque.me"
  containers:
  - name: go
    image: golang:1.25-bookworm
    command:
    - sleep
    args:
    - infinity
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - sleep
    args:
    - infinity
    resources:
        limits:
          memory: 500Mi
          ephemeral-storage: "2Gi"
    volumeMounts:
      - name: harbor-credentials
        mountPath: /kaniko/.docker
      - name: jenkins-artifacts
        mountPath: /artifacts
  volumes:
    - name: harbor-credentials
      secret:
        secretName: harbor-credentials
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: jenkins-artifacts
      persistentVolumeClaim:
        claimName: jenkins-artifacts