apiVersion: v1
kind: Secret
metadata:
  name: harbor-credentials
  namespace: jenkins
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "harbor.andrealbuquerque.me": {
          "auth": "YWRtaW46SGFyYm9yMTIzNDU="
        }
      }
    }